### PR TITLE
Remove duplicate main entry

### LINKED ISSUE #2: Multiple main definitions in package.json
The first should be removed.

### PR DESCRIPTION
**Pull request by RichardLitt**
Closes #2

### CODE REVIEW

**Comment by RichardLitt** [comment]
Ping @shamoons :)

**Comment by cherscarlett** [comment]
@shamoons please merge :)

**Comment by shamoons** [comment]
Done!

**Comment by RichardLitt** [comment]
Thanks.

**Comment by RichardLitt** [comment]
The package should be bumped, too.

**Pull request merged**
